# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs
modus_operandi: 'Pk'
#modus_operandi: 'Cl'

# Power spectrum parameters
power_params:
#    power_dir: '~/repos/hybrid_eft_nbody/data/AbacusSummit_base_c000_ph006/z1.100'
#    power_dir: '/global/cscratch1/sd/boryanah/data_hybrid/abacus/AbacusSummit_base_c000_ph006/'
    power_dir: '~/repos/hybrid_eft_nbody/data_power/'
    cullCross: 0
    joinSaccs: 1
    singleBin: 0
    lmin: kmax
    lmax: kmax
    kmin: 0.0
    kmax: 0.5
    z: 1.1 # redhift of sample - might be obsolete
    z_eff: 0.8

# Angular power spectrum parameters
cl_params:
    has_rsd: False
    has_magnification: null
    transfer_function: boltzmann_class
    matter_power_spectrum: halofit
    bg:
        b_bin0: 1.
        b_bin1: 1.
        b_bin2: 1.
        b_bin3: 1.

# Parameters for the theory templates
template_params:
#    template_dir: '/global/cscratch1/sd/boryanah/data_hybrid/abacus/AbacusSummit_base_c000_ph006/'
    template_dir: '~/repos/hybrid_eft_nbody/data/AbacusSummit_base_c000_ph006/'
    zs: [1.1, 0.8, 0.5, 0.4, 0.3, 0.2, 0.1]
    R_smooth: 0.
    Lbox: 2000.
    fields: ['1', 'b_1', 'b_2', 'b_{\nabla^2}', 'b_s']

# Parameters to be fitted in MCMC
# [mapping_index, mean, min, max, std]
fit_params:
    f_0: [0, 1., -5.0, 5.0, 0.00]
    f_1: [1, 1., -10.0, 10.0, 0.1]
    f_2: [2, 1., -10.0, 10.0, 0.1]
    f_3: [3, 1., -10.0, 10.0, 0.1]
    f_4: [4, 1., -10.0, 10.0, 0.1]
#    f_0: [0, 1., -5.0, 5.0, 0.00]
#    f_1: [1, 1., -5.0, 5.0, 1.0]
#    f_2: [2, 1., -5.0, 5.0, 1.0]
#    f_3: [3, 1., -5.0, 5.0, 1.0]
#    f_4: [4, 1., -5.0, 5.0, 1.0]

# Fixed parameters
default_params:
    Omega_b: 0.0493
    Omega_k: 0.0
    sigma8: 0.8111
    h: 0.6736
    n_s: 0.9649
    Omega_c: 0.264

# Configuration parameters for emcee
ch_config_params:
    path2output: ~/repos/hybrid_eft_nbody/chains
    chainsPrefix: test
    use_mpi: 1
    rerun: 0
    walkersRatio: 4
    burninIterations: 2000
    sampleIterations: 20000