# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs
power_dir: ['/global/cscratch1/sd/boryanah/data_hybrid/abacus/AbacusSummit_base_c000_ph006/']
template_dir: ['/global/cscratch1/sd/boryanah/data_hybrid/abacus/AbacusSummit_base_c000_ph006/']

# currently not used
cl_params:
    bg:
        b_bin0: 1.
        b_bin1: 1.
        b_bin2: 1.
        b_bin3: 1.

# currently only use kmin, kmax and zs
power_params:
    zs: [1.1, 0.8, 0.5, 0.4, 0.3, 0.2, 0.1]
    cullCross: 0
    joinSaccs: 1
    singleBin: 0
    lmin: kmax
    lmax: kmax
    kmin: 0.0
    kmax: 0.5
    path2cov: ['/global/homes/b/boryanah/repos/hybrid_eft_nbody/data/covmat.npy']

template_params:
    R_smooth: 0.

# Parameters to be fitted in MCMC
# [mapping_index, mean, min, max, std]
fit_params:
    f_0: [0, 1., -10.0, 10.0, 0.00]
    f_1: [1, 1., -10.0, 10.0, 1.1]
    f_2: [2, 1., -10.0, 10.0, 1.1]
    f_3: [3, 1., -10.0, 10.0, 1.1]
    f_4: [4, 1., -10.0, 10.0, 1.1]

# currently not used
default_params:
    has_rsd: False
    has_magnification: null
    Omega_b: 0.0493
    Omega_k: 0.0
    sigma8: 0.8111
    h: 0.6736
    n_s: 0.9649
    Omega_c: 0.264
    Lbox: 2000.
#    transfer_function: boltzmann_class
#    matter_power_spectrum: halofit

# Configuration parameters for emcee
ch_config_params:
    path2output: //global/homes/b/boryanah/repos/hybrid_eft_nbody/chains
    chainsPrefix: test
    use_mpi: 1
    rerun: 0
    walkersRatio: 8
    burninIterations: 2000
    sampleIterations: 40000